# test 1
python viz.py --problem ./ipc_problem_files/instance-19.pddl --plan ./results/pddl_results/merge-and-shrink/plan-19.txt 

#test 2
python viz.py --problem ./ipc_problem_files/instance-8.pddl --plan ./results/pddl_results/merge-and-shrink/plan-8.txt

#test 3 -- using a plan generated by DeepCubeA for visualization 
python viz.py --dc 1 --problem ./ipc_problem_files/instance-14.pddl --plan ./results/dc_results/plan-14.txt